<?php

return [
    [
        'name' => 'Manzano',
        'scientific_name' => 'Malus domestica',
        'description' => 'Árbol frutal de la familia Rosáceas.',
        'family_id' => 1,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Cerezo',
        'scientific_name' => 'Prunus avium',
        'description' => 'Árbol de la familia Rosáceas con frutos rojos.',
        'family_id' => 1,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Almendro',
        'scientific_name' => 'Prunus dulcis',
        'description' => 'Árbol de la familia Rosáceas conocido por sus almendras.',
        'family_id' => 1,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Roble Común',
        'scientific_name' => 'Quercus robur',
        'description' => 'Árbol de hojas caducas de la familia Fagáceas.',
        'family_id' => 2,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Encina',
        'scientific_name' => 'Quercus ilex',
        'description' => 'Árbol de hojas perennes de la familia Fagáceas.',
        'family_id' => 2,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Castaño',
        'scientific_name' => 'Castanea sativa',
        'description' => 'Árbol de la familia Fagáceas con frutos comestibles.',
        'family_id' => 2,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Pino Blanco',
        'scientific_name' => 'Pinus strobus',
        'description' => 'Árbol de hojas perennes de la familia Pináceas.',
        'family_id' => 3,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Pino Oregón',
        'scientific_name' => 'Pseudotsuga menziesii',
        'description' => 'Árbol alto de la familia Pináceas utilizado en carpintería.',
        'family_id' => 3,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Cedro Blanco',
        'scientific_name' => 'Thuja occidentalis',
        'description' => 'Árbol de madera aromática de la familia Pináceas.',
        'family_id' => 3,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Abedul de Canadá',
        'scientific_name' => 'Betula papyrifera',
        'description' => 'Árbol de la familia Betuláceas conocido por su corteza.',
        'family_id' => 4,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Arrayán Común',
        'scientific_name' => 'Myrtus communis',
        'description' => 'Árbol de la familia Myrtáceas con hojas aromáticas.',
        'family_id' => 5,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Palma Datilera',
        'scientific_name' => 'Phoenix dactylifera',
        'description' => 'Árbol de la familia Arecáceas conocido por sus dátiles.',
        'family_id' => 6,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Ciprés de Lawson',
        'scientific_name' => 'Chamaecyparis lawsoniana',
        'description' => 'Árbol ornamental de la familia Cupresáceas.',
        'family_id' => 7,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Higuera Común',
        'scientific_name' => 'Ficus carica',
        'description' => 'Árbol de la familia Moráceas con higos comestibles.',
        'family_id' => 8,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Zapote Negro',
        'scientific_name' => 'Diospyros texana',
        'description' => 'Árbol de la familia Sapotáceas con frutos oscuros.',
        'family_id' => 9,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Mango Alphonso',
        'scientific_name' => 'Mangifera indica',
        'description' => 'Variedad de mango de la familia Anacardiáceas.',
        'family_id' => 10,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Robinia Pseudoacacia',
        'scientific_name' => 'Robinia pseudoacacia',
        'description' => 'Árbol de la familia Leguminosas con flores fragantes.',
        'family_id' => 11,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Sándalo Rojo',
        'scientific_name' => 'Pterocarpus santalinus',
        'description' => 'Árbol de la familia Leguminosas con madera roja aromática.',
        'family_id' => 11,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Catalpa del Norte',
        'scientific_name' => 'Catalpa speciosa',
        'description' => 'Árbol de la familia Bignonáceas con flores en forma de trompeta.',
        'family_id' => 12,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Naranjo',
        'scientific_name' => 'Citrus sinensis',
        'description' => 'Árbol de la familia Rutáceas conocido por sus naranjas.',
        'family_id' => 13,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Limonero Meyer',
        'scientific_name' => 'Citrus limon',
        'description' => 'Variedad de limonero de la familia Rutáceas.',
        'family_id' => 13,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Ginseng Americano',
        'scientific_name' => 'Panax quinquefolius',
        'description' => 'Variedad de ginseng de la familia Araliáceas.',
        'family_id' => 14,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Olivo Arbequina',
        'scientific_name' => 'Olea europaea',
        'description' => 'Variedad de olivo de la familia Oleáceas conocida por su aceite.',
        'family_id' => 15,
        'location' => 'Lambayeque',
    ],
    [
        'name' => 'Fresno Común',
        'scientific_name' => 'Fraxinus excelsior',
        'description' => 'Árbol de la familia Oleáceas utilizado en la fabricación de bates de béisbol.',
        'family_id' => 15,
        'location' => 'Lambayeque',
    ],
];
